FROM mcr.microsoft.com/mssql/server:2022-CU13-ubuntu-22.04

USER root

RUN apt-get update && \
    ACCEPT_EULA=Y apt-get install -y \
        mssql-tools18 \
        unixodbc-dev && \
    echo 'export PATH="$PATH:/opt/mssql-tools18/bin"' > /etc/profile.d/mssql-tools.sh

USER mssql
