// <auto-generated />
using System;
using FirstNETWebApp.Infrastructure.Database.EntityFramework;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FirstNETWebApp.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20260122103006_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BodyTrack", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date")
                        .HasColumnName("date");

                    b.Property<double>("Height")
                        .HasColumnType("float")
                        .HasColumnName("height");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("userId");

                    b.Property<double>("Weight")
                        .HasColumnType("float")
                        .HasColumnName("weight");

                    b.HasKey("Id")
                        .HasName("PK__BodyTrac__3213E83F9376C573");

                    b.HasIndex("UserId");

                    b.ToTable("BodyTracks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Date = new DateOnly(2025, 1, 1),
                            Height = 186.0,
                            UserId = 1,
                            Weight = 71.099999999999994
                        },
                        new
                        {
                            Id = 2,
                            Date = new DateOnly(2025, 1, 1),
                            Height = 175.0,
                            UserId = 2,
                            Weight = 68.5
                        });
                });

            modelBuilder.Entity("Exercise", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("imageUrl");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("name");

                    b.Property<string>("TargetMuscle1")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("targetMuscle1");

                    b.Property<string>("TargetMuscle2")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("targetMuscle2");

                    b.Property<string>("TargetMuscle3")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("targetMuscle3");

                    b.HasKey("Id")
                        .HasName("PK__Exercise__3213E83F5F5DCFD7");

                    b.ToTable("Exercises");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ImageUrl = "https://example.com/bench.png",
                            Name = "bench press",
                            TargetMuscle1 = "Chest",
                            TargetMuscle2 = "Triceps",
                            TargetMuscle3 = "Shoulders"
                        },
                        new
                        {
                            Id = 2,
                            ImageUrl = "https://example.com/squat.png",
                            Name = "squat",
                            TargetMuscle1 = "Quads",
                            TargetMuscle2 = "Glutes"
                        });
                });

            modelBuilder.Entity("Plan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("MembershipTier")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("membershipTier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("name");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("userId");

                    b.HasKey("Id")
                        .HasName("PK__Plans__3213E83FDE6669F9");

                    b.HasIndex("UserId");

                    b.ToTable("Plans");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            MembershipTier = "basic",
                            Name = "beginner strength",
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            MembershipTier = "basic",
                            Name = "upper body focus",
                            UserId = 2
                        });
                });

            modelBuilder.Entity("Session", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date")
                        .HasColumnName("date");

                    b.Property<int?>("PlanId")
                        .HasColumnType("int")
                        .HasColumnName("planId");

                    b.HasKey("Id")
                        .HasName("PK__Session__3213E83F0BBAD9DE");

                    b.HasIndex("PlanId");

                    b.ToTable("Session", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Date = new DateOnly(2025, 1, 10),
                            PlanId = 1
                        },
                        new
                        {
                            Id = 2,
                            Date = new DateOnly(2025, 1, 12),
                            PlanId = 2
                        });
                });

            modelBuilder.Entity("Set", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ExerciseId")
                        .HasColumnType("int")
                        .HasColumnName("exerciseId");

                    b.Property<int>("Reps")
                        .HasColumnType("int")
                        .HasColumnName("reps");

                    b.Property<int>("RestTime")
                        .HasColumnType("int")
                        .HasColumnName("restTime");

                    b.Property<int>("SessionId")
                        .HasColumnType("int")
                        .HasColumnName("sessionId");

                    b.Property<int>("Weight")
                        .HasColumnType("int")
                        .HasColumnName("weight");

                    b.HasKey("Id")
                        .HasName("PK__Sets__3213E83F473FF2E9");

                    b.HasIndex("ExerciseId");

                    b.HasIndex("SessionId");

                    b.ToTable("Sets");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ExerciseId = 1,
                            Reps = 10,
                            RestTime = 90,
                            SessionId = 1,
                            Weight = 60
                        },
                        new
                        {
                            Id = 2,
                            ExerciseId = 1,
                            Reps = 8,
                            RestTime = 120,
                            SessionId = 1,
                            Weight = 65
                        },
                        new
                        {
                            Id = 3,
                            ExerciseId = 2,
                            Reps = 12,
                            RestTime = 120,
                            SessionId = 2,
                            Weight = 80
                        });
                });

            modelBuilder.Entity("User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("email");

                    b.Property<string>("MembershipTier")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Basic")
                        .HasColumnName("membershipTier");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("password");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("username");

                    b.HasKey("Id")
                        .HasName("PK__Users__3213E83FE8E97ABC");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "dummyemail1@gmail.com",
                            MembershipTier = "Basic",
                            Password = "akmfsapmfpkmfdsapmfwe",
                            Username = "dummyUsername1"
                        },
                        new
                        {
                            Id = 2,
                            Email = "dummyemail2@gmail.com",
                            MembershipTier = "Basic",
                            Password = "yiueoipkwemrkwerewerw",
                            Username = "dummyUsername2"
                        },
                        new
                        {
                            Id = 3,
                            Email = "dummyemail3@gmail.com",
                            MembershipTier = "Basic",
                            Password = "svfsdhkjyuiyuiertetrr",
                            Username = "dummyUsername3"
                        });
                });

            modelBuilder.Entity("BodyTrack", b =>
                {
                    b.HasOne("User", "User")
                        .WithMany("BodyTracks")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_BodyTracks_Users");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Plan", b =>
                {
                    b.HasOne("User", "User")
                        .WithMany("Plans")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_Plans_Users");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Session", b =>
                {
                    b.HasOne("Plan", "Plan")
                        .WithMany("Sessions")
                        .HasForeignKey("PlanId")
                        .HasConstraintName("FK_Session_Plans");

                    b.Navigation("Plan");
                });

            modelBuilder.Entity("Set", b =>
                {
                    b.HasOne("Exercise", "Exercise")
                        .WithMany("Sets")
                        .HasForeignKey("ExerciseId")
                        .IsRequired()
                        .HasConstraintName("FK_Sets_Exercises");

                    b.HasOne("Session", "Session")
                        .WithMany("Sets")
                        .HasForeignKey("SessionId")
                        .IsRequired()
                        .HasConstraintName("FK_Sets_Session");

                    b.Navigation("Exercise");

                    b.Navigation("Session");
                });

            modelBuilder.Entity("Exercise", b =>
                {
                    b.Navigation("Sets");
                });

            modelBuilder.Entity("Plan", b =>
                {
                    b.Navigation("Sessions");
                });

            modelBuilder.Entity("Session", b =>
                {
                    b.Navigation("Sets");
                });

            modelBuilder.Entity("User", b =>
                {
                    b.Navigation("BodyTracks");

                    b.Navigation("Plans");
                });
#pragma warning restore 612, 618
        }
    }
}
