#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

dotnet build ./src/FirstNETWebApp.csproj

dotnet build ./tests/FirstNETWebApp.Tests.csproj

dotnet format ./src/FirstNETWebApp.csproj --verify-no-changes

dotnet format ./tests/FirstNETWebApp.Tests.csproj --verify-no-changes